info:
  component: Dummy Service
  
spring:
 application:
  name: dummy-service
  
 
eureka:
 client:
  serviceUrl: 
   defaultZone: http://localhost:1111/eureka/
  healthcheck:
   enabled: true 
 instance:
  hostname: localhost
  preferIpAddress: false
  leaseRenewalIntervalInSeconds: 30 # DO NOT DO THIS IN PRODUCTION
  metadata-map:
   management:
    port: ${server.port}
 
 